project_1/wiki/wiki/encyclopedia/urls.py
from django.urls import path

from . import views


app_name = "encyclopedia"

urlpatterns = [
    path("", views.index, name="index"),
    path("create", views.create, name="create"),
    path("random", views.random_page, name="random"),
    path("entry", views.entry, name="entry"),
    path("edit", views.edit, name="edit"),
    path("saved", views.saved, name="saved"),
]

project_1/wiki/wiki/wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

project_1/wiki/wiki/encyclopedia/views.py
from django.shortcuts import render
from django.shortcuts import HttpResponseRedirect
from django.urls import reverse
from . import util
import markdown2
from markdown2 import Markdown
import random

def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })

def create(request):

    if request.method == "POST":

        title = request.POST.get("title")
        content = request.POST.get("content")

        if title and content:
            if util.get_entry(title):
                return render(request, "encyclopedia/error.html", {
                    "error": f"Entry already exists sorry."
                })
            
            util.save_entry(title, content)
            return render(request, "encyclopedia/created.html", {
                "entry_title": title    
            })
        
        else:

            return render(request, "encyclopedia/error.html", {
                "error": f"One or both fields are empty please try again"
            })
                
    else:

        return render(request, "encyclopedia/create.html")

def random_page(request):
    
    if request.method == "POST":
    
        entries = util.list_entries()

        entry = random.choice(entries)

        return render(request, "encyclopedia/entry.html", {
            "entry_title": entry,
            "entry": util.get_entry(entry),
            "entry_markdown2": markdown2.markdown(util.get_entry(entry))
        })
    
    else:
        return render(request, "encyclopedia/random.html")
    
def entry(request):

    if request.method == "POST":

        
        entry = request.POST.get("entry")

        if util.get_entry(entry):

            return render(request, "encyclopedia/entry.html", {
                "entry_title": entry,
                "entry": util.get_entry(entry),
                "entry_markdown2": markdown2.markdown(util.get_entry(entry))
            })
        else:
            entries = util.list_entries()
            matching_titles = []

            for title in entries:
                if entry in title:
                    matching_titles.append(title)
            
            if not matching_titles:
                return render(request, "encyclopedia/error.html", {
                    "error": f"No entries here :("
                })
            else:
                print(matching_titles)
                return render(request, "encyclopedia/suggestions.html", {
                    "matching_titles": matching_titles
                })
    
    else:
        
        return HttpResponseRedirect(reverse("encyclopedia:index"))

def edit(request):
    
    if request.method == "POST":

        entry_title = request.POST.get("entry_title")
        entry = request.POST.get("entry")

        return render(request, "encyclopedia/edit.html", {
            "entry_title": entry_title,
            "entry": entry
        })
    
    else:
        return HttpResponseRedirect(reverse("encyclopedia:index"))
    
def saved(request):
    
    if request.method == "POST":
        
        entry_title = request.POST.get("entry_title")
        entry = request.POST.get("entry")

        util.save_entry(entry_title,entry)

        return render(request, "encyclopedia/saved.html", {
            "entry_title": entry_title
        })
    
    else:
        return HttpResponseRedirect(reverse("encyclopedia:index"))

project_1/wiki/wiki/encyclopedia/templates/encyclopedia/create.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Create
{% endblock %}

{% block body %}

<form action="{% url 'encyclopedia:create' %}" method="POST">
    {% csrf_token %}

    <div>
        <label for="title">Name of entry?:</label>
        <input type="text" name="title">
    </div>
    <br>

    <div>
        <textarea name="content" rows="2" columns="40">
            Enter text here:
        </textarea>
    </div>
    
    <button type="submit">Save Page</button>

</form>

{% endblock %}

project_1/wiki/wiki/encyclopedia/templates/encyclopedia/created.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
     Created 
{% endblock %}

{% block body %}
 
<h2>Your edits for entry named: {{ entry_title }},   have been created. Thank you!</h2>
<a href="{% url 'encyclopedia:index' %}">Click here to return home</a>

<form action="{% url 'encyclopedia:entry' %}" method="POST">
    {% csrf_token %}
    <input type="hidden" name="entry" value="{{ title }}">
    <button type="submit" style="border: none; background: none; padding: 0; font: inherit; cursor: pointer; text-decoration: underline; color: blue;">{{ title }}</button>
</form>

{% endblock %}

project_1/wiki/wiki/encyclopedia/templates/encyclopedia/edit.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{ entry_title }} | edit
{% endblock %}

{% block body %}
    <div>
        <textarea name="content" rows="2" column="40">
            {{ entry }}
        </textarea> 
    </div>

    <div>
        <form action="{% url 'encyclopedia:saved' %}" method="POST">
            {% csrf_token %}
            <input type="hidden" name="entry_title" value="{{ entry_title }}">
            <input type=hidden name="entry" value="{{ entry }}">
            <button type="submit">Save changes</button>
        </form>
    </div>

{% endblock %}

project_1/wiki/wiki/encyclopedia/templates/encyclopedia/entry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
     {{ entry_title }} 
{% endblock %}

{% block body %}
 
<div>
     {{ entry_markdown2|safe }} 
</div>

<div>
     <form action="{% url 'encyclopedia:edit' %}" method="POST">
          {% csrf_token %}
          <input type="hidden" name="entry_title" value="{{ entry_title }}">
          <input type="hidden" name="entry" value="{{ entry }}">
          <button type="submit">Edit</button>
     </form>
</div>

{% endblock %}

project_1/wiki/wiki/encyclopedia/templates/encyclopedia/error.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Error
{% endblock %}

{% block body %}

    <h2>{{ error }}</h2>

{% endblock %}

project_1/wiki/wiki/encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li>{{ entry }}</li>
        {% endfor %}
    </ul>

{% endblock %}

project_1/wiki/wiki/encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'encyclopedia:entry' %}" method="POST">
                    {% csrf_token %}
                    <input class="search" type="text" name="entry" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:create' %}">Create new page</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:random' %}">Random page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

project_1/wiki/wiki/encyclopedia/templates/encyclopedia/nothing.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Nothing Here
{% endblock %}

{% block body %}
    
    <p>
        <h2>
            No entry was found &#x1F643;
        </h2>
    </p>
 
{% endblock %}

project_1/wiki/wiki/encyclopedia/templates/encyclopedia/qristaan.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Qristaan
{% endblock %}

{% block body %}
   
    qristaan

{% endblock %}

project_1/wiki/wiki/encyclopedia/templates/encyclopedia/random.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Random Page
{% endblock %}

{% block body %}
    
<h2>
    <form method="post" action="{% url 'encyclopedia:random' %}">
        {% csrf_token %}
        <button type="submit">Click Here to Genereate Randomn Page</button>
    </form>
</h2>
    

{% endblock %}


project_1/wiki/wiki/encyclopedia/templates/encyclopedia/saved.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
     Saved 
{% endblock %}

{% block body %}
 
<h2>Your edits for entry named: {{ entry_title }},   have been saved. Thank you!</h2>
<a href="{% url 'encyclopedia:index' %}">Click here to return home</a>

{% endblock %}

project_1/wiki/wiki/encyclopedia/templates/encyclopedia/suggestions.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Suggestions
{% endblock %}

{% block body %}

<h2>Did you mean to visit? :</h2>
    
{% for title in matching_titles %}

    <ul>
        <form action="{% url 'encyclopedia:entry' %}" method="POST">
            {% csrf_token %}
            <input type="hidden" name="entry" value="{{ title }}">
            <button type="submit" style="border: none; background: none; padding: 0; font: inherit; cursor: pointer; text-decoration: underline; color: blue;">{{ title }}</button>
        </form>
    </ul>

{% endfor %}
 
{% endblock %}